/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Person } from "./components/my-rating/my-rating";
export namespace Components {
    interface MyRating {
        "getValue": (params: any) => Promise<number>;
        "isShow": boolean;
        "maxValue": number;
        "person": object;
        "personArray": Person[];
        "setPerson": (params: any) => Promise<boolean>;
        "setPersonArray": (persons: []) => Promise<boolean>;
        "value": number;
    }
}
declare global {
    interface HTMLMyRatingElement extends Components.MyRating, HTMLStencilElement {
    }
    var HTMLMyRatingElement: {
        prototype: HTMLMyRatingElement;
        new (): HTMLMyRatingElement;
    };
    interface HTMLElementTagNameMap {
        "my-rating": HTMLMyRatingElement;
    }
}
declare namespace LocalJSX {
    interface MyRating {
        "isShow"?: boolean;
        "maxValue"?: number;
        "onRatingChange"?: (event: CustomEvent<any>) => void;
        "person"?: object;
        "personArray"?: Person[];
        "value"?: number;
    }
    interface IntrinsicElements {
        "my-rating": MyRating;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-rating": LocalJSX.MyRating & JSXBase.HTMLAttributes<HTMLMyRatingElement>;
        }
    }
}
